# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateTimeField(verbose_name=b'date')),
                ('content', models.TextField()),
                ('reply', models.TextField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogersite.Posts')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
